### ISSUE TITLE
Warm-up fetch

### ISSUE THREAD

**Issue by pebezo** [FransBouma/RawDataAccessBencher#21]
Before running the set fetch you perform a warm-up grab that you discard. Any reason why you don't also discard the first single element? From what I see, the first single element request weighs more than the subsequent requests -- looking at Dapper -- which skews the results a bit.

**Comment by FransBouma** [comment]
That might be a bug. I recently switched from 'throw the slowest+fastest away' to calculating mean+stddev, so keeping all results but added an ignore for the first fetch of the set of course as that would skew the results. If I have forgotten to add that for the individual fetches then that's a bug. Will look into it.

**Comment by pebezo** [comment]
I made the change as part of the PR. Now that I look at it I should've called it after ReportSetResult(bencher, result); and called "ReportSetResult(bencher, result);" again after bencher.PerformIndividualBenchMark(KeysForIndividualFetches, discardResults: true); The results should be the same (nicer output though).

**Comment by FransBouma** [comment]
Yes, saw that, good call. I've kept it in the merged code :)
