### ISSUE TITLE
Update for EF Core 1.0

### ISSUE THREAD

**Issue by ErikEJ** [FransBouma/RawDataAccessBencher#29]
Would be great if you could update measurements for EF Core 1.0

**Comment by FransBouma** [comment]
Will do shortly :) Code is already updated for 1.0 RTM. I've run it privately already but not published it yet. Numbers are on par with RC2, a bit slower perhaps but nothing shocking.

**Comment by ErikEJ** [comment]
Thanks, Frans - good to hear!

**Comment by FransBouma** [comment]
Live now, see repo :)
