### ISSUE TITLE
EF Core 2.0 benchmark

### ISSUE THREAD

**Issue by ErikEJ** [FransBouma/RawDataAccessBencher#35]
Is missing

**Comment by FransBouma** [comment]
Noted. When EF core 2.0 support is added to llblgen pro v5.3 (some time in the coming weeks), I'll update the benchmark with EF 2.0 and also with v5.3 runtimes and other updated frameworks.

**Comment by FransBouma** [comment]
Implemented.
https://github.com/FransBouma/RawDataAccessBencher/blob/master/Results/2017-09-25.txt

Not really that great, tbh. they're slowly slipping away, and with a lot of features still to be added, I doubt they'll be faster in the future, on the contrary. 

Haven't looked at memory consumption yet. Last time it was terrible but perhaps they've done a lot in that area, not sure. Will try to add BenchmarkDotnet support to make that easier to test

**Comment by ErikEJ** [comment]
@divega FYI!
