### ISSUE TITLE
Update Benchers for EF6, EF Core and PetaPoco

### ISSUE THREAD

**Issue by jonnybee** [FransBouma/RawDataAccessBencher#55]
Update .NET project s to .NET 4.8 and NET Core  projects to .NET5

Update benchers for EF6 and EF Core so that:
* EF6 benchers run in both .NET 4.8 and NET5
* Update EF Core benchers to use EF Core 3.1 in .NET4.8 and EF Core 5 in .NET5
* Update EF Core DTO bencher to run in Both .NET4.8 and .NET5
* Update PetaPoco benchers to use PetaPoco.Compiled v6

**Comment by FransBouma** [comment]
Implemented in #56
